spring:
  application:
    name: ecommerce-api

database:
  host: ${DB_HOST}
  name: ${DB_NAME}
  user: ${DB_USER}
  pwd: ${DB_PASSWORD}
  port: ${DB_PORT}

server:
  url: ${SERVER_URL}
  secret: ${SERVER_SECRET}