spring:
  application:
    name: ecommerce-api
  data:
    mongodb:
      auto-index-creation: true

database:
  host: ${DB_HOST}
  name: ${DB_NAME}
  user: ${DB_USER}
  pwd: ${DB_PASSWORD}
  port: ${DB_PORT}

server:
  url: ${SERVER_URL}
  secret: ${SERVER_SECRET}

gateways:
  payment:
    url: ${PAYMENT_GW_URL}
    key: ${PAYMENT_GW_KEY}